"""test revision

Revision ID: 6605d3e04f20
Revises: 3c4b06dfa46d
Create Date: 2024-09-06 00:23:45.953491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6605d3e04f20'
down_revision: Union[str, None] = '3c4b06dfa46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('email', sa.String, nullable=False),
                    sa.Column('username', sa.String, nullable=False),
                    sa.Column('hashed_password', sa.String, nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
