"""test

Revision ID: eee8febd597a
Revises: 6605d3e04f20
Create Date: 2024-09-06 12:42:30.824833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee8febd597a'
down_revision: Union[str, None] = '6605d3e04f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('figi', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('instrument_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='operation_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
